# Generated by Django 5.0 on 2024-06-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratingstar",
            options={
                "ordering": ["-value"],
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
            },
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.PositiveSmallIntegerField(
                default=2019, verbose_name="Дата выхода"
            ),
        ),
    ]
