repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args:
          - --namespace-packages
          - --ignore-missing-imports
        additional_dependencies:
          - requests
          - types-requests

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.0
    hooks:
      - id: black
